import React,{createContext,useState} from 'react'

export const Store=createContext();
const ContextAPI = (props) => {
    const[data,setData]=useState([
       { id:1,
        cat:'Bollywood',
        name:'Gadar2 breaks the box Office, Sunny Deol comments',
      heading:'Gadar 2 first look poster out; Sunny Deol and Ameesha Patel film to be released on Independence Day 2023.Sunny Deol and Ameesha Patel film to be released on Independence Day 2023.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.hindustantimes.com/img/2023/01/26/550x309/gadar_2_1674715753204_1674715789861_1674715789861.jfif',
       },
       { id:2,
        cat:'Bollywood',
        name:'When Amitabh Bachchan got a ‘complex’',
      heading:'When Amitabh Bachchan got a ‘complex’ after working with Tinnu Anand on Agneepath: ‘I was abusing so much Amitabh got a complex’ Tinnu Anand recalled how he was briefed for his role ',description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.indianexpress.com/2023/09/amitabh-bachchan-1.jpg?w=640',
       },
       { id:3,
        cat:'Bollywood',
        name:'Jawan song ‘Chaleya’ breaks record',
      heading:'Jawan song ‘Chaleya’ breaks record for most streams in a single day on Spotify India. "Chaleya," performed by Anirudh Ravichander, Arijit Singh and Shilpa Rao, appears to be the most popular song from Jawan soundtrack album.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://i0.wp.com/www.fsicareer.com/wp-content/uploads/2023/08/Jawan-Song-Chaleya-Out-Now.jpg',
       },
       { id:4,
        cat:'Bollywood',
        name:'Manish Malhotra Fixes Rekha Not-A-Saree On The Red Carpet.',
      heading:'Rekha has been serving back-to-back perfect looks throughout the year. A little background for those who require one. Earlier this year, she shared the carpet with Kajol and Nysa Devgan...',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://c.ndtvimg.com/2023-09/27fj25e8_rekha_625x300_14_September_23.jpeg',
       },
       { id:5,
        cat:'Bollywood',
        name:'Parineeti Chopra and Raghav Chaddha wedding',
      heading:'Parineeti Chopra and Raghav Chaddha wedding details out; date, theme, venue and more.Parineeti Chopra and Raghav Chadha will reportedly be tying the knot in a grand destination wedding ceremony on September 24.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://assets.vogue.in/photos/645fb0f924adb5caa6323e2f/master/w_1600%2Cc_limit/346109843_288596650179546_5963840803101851232_n.jpg',
       },
       { id:6,
        cat:'Bollywood',
        name:'Natasha Poonawalla has shared a carousel from the “most fun party.',
        heading:' After Lauren Sanchez, Natasha Poonawalla has given a shout out to actress Salma Hayek for a “fun, thoughtful, and inspiring evening.” FYI: She was among the guests who attended the 15th anniversary of the Kering Foundation”',
        description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://c.ndtvimg.com/2023-09/n2pg99bo_natasha_625x300_14_September_23.jpg',
       },
       { id:7,
        cat:'Bollywood',
        name:'Shah Rukh Khan responds as Soni Razdan',
      heading:'Shah Rukh Khan responds as Soni Razdan, Mahesh Bhatt go on a movie date for Jawan, Karan Johar ‘bows down’ to SRK mega-stardom Karan Johar has taken to Instagram to laud Jawan and called Shah Rukh Khan the emperor.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.indianexpress.com/2023/09/Soni.jpg?w=640',
       },
       { id:8,
        cat:'Bollywood',
        name:'Karan Johar says his kids think he talks a lot on TV and it boring',
      heading:'Karan Johar says his kids think he talks a lot on TV and it boring: They refused to watch Rocky Aur Rani Karan Johar said that his kids have no interest in Bollywood and donot even know...',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.bollywoodhungama.com/wp-content/uploads/2021/11/WhatsApp-Image-2021-11-04-at-4.24.00-PM.jpeg',
       },
       { id:9,
        cat:'Bollywood',
        name:'Suhana Khan shares her take on beauty',
      heading:'Suhana Khan shares her take on beauty, Arjun Kapoor says, She does sound like someone daughter Suhana Khan thinks that Gen Z is redefining the team beauty and giving it more layers and depth and its more .',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/09/suhana-khan-16946653913x2.jpg',
       },
       { id:10,
        cat:'Bollywood',
        name:'Ameesha Patel says her most expensive luxury bag',
      heading:'Ameesha Patel says her most expensive luxury bag costs Rs 70 lakh: ‘You can buy a house in place of this bag Ameesha Patel showed off her luxury bag collection and shared that the most expensive bag ',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://i.ytimg.com/vi/sUIWHTv3YiE/maxresdefault.jpg',
       },
       { id:11,
        cat:'Bollywood',
        name:'Kiran Rao on a ‘wonderful relationship’ with ex-husband Aamir Khan',
      heading:'Kiran Rao on a ‘wonderful relationship’ with ex-husband Aamir Khan, finding support from his family after divorce: Never had trauma Kiran Rao said that she is fortunate to have a healthy relationship with ex-husband Aamir Khan .',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/2022/03/14/1022711-aamir-khan-kiran-rao.png',
       },
       { id:12,
        cat:'Bollywood',
        name:'Tabu, Ali Fazal and Wamiqa Gabbi are in the dark',
      heading:'Tabu, Ali Fazal and Wamiqa Gabbi are in the dark as they tease Vishal Bhardwaj’s Khufiya. Watch announcement video Vishal Bhardwaj has officially announced his highly anticipated film...',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://i2.cinestaan.com/image-bank/1500-1500/191001-192000/191984.jpg',
       },
       { id:13,
        cat:'Bollywood',
        name:'Alia Bhatt shares poolside pics',
      heading:'Alia Bhatt shares poolside pics to give a glimpse of her ‘day-off schedule’, Arjun Kapoor replies ‘Need this in my life’ Alia Bhatt took to social media to give a glimpse of her me time on her day-off. It led her Two States co-actor Arjun Kapoor to also want the same.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.hindustantimes.com/img/2021/12/17/1600x900/alia_bhatt_1639741092345_1639741092483.jpg',
       },
       { id:14,
        cat:'Bollywood',
        name:'Deepika Padukone noticed Ridhi Dogra was sitting separately on set',
      heading:'Deepika Padukone noticed Ridhi Dogra was sitting separately on set, so she moved her seat closer to hers: Jawan actor recalls kind gesture Ridhi Dogra shared a heartwarming anecdote from the sets of the Shah Rukh Khan-starrer Jawan that showcased Deepika Padukone kindness and generosity.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.indianexpress.com/2023/09/Ridhi.jpg',
       },
       { id:15,
        cat:'Bollywood',
        name:'Abhishek Bachchan says he doesn’t do ‘heavy lifting at home’',
      heading:'Abhishek Bachchan says he doesn’t do ‘heavy lifting at home’, it’s entirely done by Aishwarya Rai: ‘She allows me to go and do my work’ Abhishek Bachchan, father of soon-to-be teenager Aaradhya, revealed he had questioned his sister Shweta Bachchan when her kids were given phones at the age of 10.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://im.indiatimes.in/content/2023/Sep/abhishek-bachchan-says-aishwarya-rai-does-all-the-heavy-lifting-at-home_650157a9e1607.jpg?w=820&h=540&cc=1',
       },
       { id:16,
        cat:'Hollywood',
        name:'Tom Sandoval opens up about public life after Raquel Leviss affair',
      heading:'‘It’s probably going to get worse before it gets better’: Tom Sandoval opens up about public life after Raquel...The Vanderpump Rules star exclusively talked to PEOPLE ',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-09/530902678_screenshot-2023-09-14-at-1-24-27-pm.jpg',
       },
       { id:17,
        cat:'Hollywood',
        name:'Where did Riley Keough meet husband Ben Smith-Petersen?',
      heading:'Where did Riley Keough meet husband Ben Smith-Petersen? Take a look at the couple’s relationship timeline The late Lisa Marie Presley’s daughter Riley Keough got married to beau Ben .',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-01/1345768762_riley-keough-ben-smith-petersen_1280*720.jpg',
       },
       { id:18,
        cat:'Hollywood',
        name:'Cartoon Network says ‘We are not dead, not going anywhere’',
      heading:'Cartoon Network says ‘We are not dead, not going anywhere’ after #RIPCartoonNetwork trends on social media Soon after reports surfaced claiming that Cartoon Network.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2022-10/503604372_fe9t5cswyae6c6j_1280*720.jpg',
       },
       { id:19,
        cat:'Hollywood',
        name:'Park So Dam responds to malicious DMs',
      heading:'Park So Dam responds to malicious DMs: Netizens suspect Record of Youth co-star Park Bo Gum’s fan Parasite star Park So Dam takes the high road in response to hate messages, says will promote .',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-01/1709027301_307583574_8080604262012441_3450944865193181309_n_1280*720.jpg',
       },
       { id:20,
        cat:'Hollywood',
        name:'Lisa Marie Presley’s daughter Riley Keough',
      heading:'Lisa Marie Presley’s daughter Riley Keough and husband Ben Smith-Petersen secretly welcomed their first child? Ben Smith-Petersen read a letter on behalf of wife Riley Keough at Lisa Marie Presley ',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-01/96675590_riley-keough-ben-smith-petersen-1_1280*720.jpg',
       },
       { id:21,
        cat:'Hollywood',
        name:'Julia Roberts discovers',
      heading:'Julia Roberts discovers she is not actually a ‘Roberts’ after DNA test; 7 interesting facts about the actress Julia Roberts has learned a secret about her ancestry related to her great-great-grandmother Rhoda Suttle Roberts. Find out more interesting details about her.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-01/727497862_julia-roberts-dna-ancestry_1280*720.jpg',
       },
       { id:22,
        cat:'Hollywood',
        name:'Priyanka Chopra in Sergio Hudson',
      heading:'Priyanka Chopra in Sergio Hudson, Alaïa, Vivienne Westwood and Michael Kors showed dresses for days like a pro There a hot wave in here. Is it something to be concerned or excited about? It the latter absolutely. Here how Priyanka Chopra is giving all new meanings to dresses.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-01/1662308084__1280*720.jpg',
       },
       { id:23,
        cat:'Hollywood',
        name:'Is Selena Gomez dating Chainsmokers’ Drew Taggart?',
      heading:'Is Selena Gomez dating Chainsmokers’ Drew Taggart? A brief look into the actress’ dating history Selena Gomez and Drew Taggart have reportedly hit it off together. Read the article to know more details about their romance and Selena’s dating history.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-01/201276289_selena-gomez-drew-taggart-relationship_1280*720.jpg',
       },
       { id:24,
        cat:'Hollywood',
        name:'Top 7 VMAs moments',
      heading:'Top 7 VMAs moments: From Taylor Swift creating history, Ice Spices debut Selena-Taylor reunion and more Here are some of the best moments from VMAs 2023 that range from Taylor  Award to Ice Spice award debut',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-09/1373832792_shakira-getty.jpg',
       },
       { id:25,
        cat:'Hollywood',
        name:'Are Taylor Swift and Travis Kelce ‘quietly’ hanging out?',
      heading:'Are Taylor Swift and Travis Kelce ‘quietly’ hanging out? Report suggests so As per reports, Taylor Swift and Travis Kelce have been quietly hanging out. The duo first met in New York City a few weeks ago. Read to find out.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-09/1138513139_taylor-swift-and-travis-kelce.jpg',
       },
       { id:26,
        cat:'Hollywood',
        name:'From TXT Back For More performance to Stray Kids winning',
      heading:'From TXT Back For More performance to Stray Kids winning: Top K-pop 2023 MTV VMAs moments The ever-popular 2023 MTV VMAs aired on September 13th, and needless to say, K-pop shined through in multiple categories. Pick your favorite K-pop moment from the award show.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-09/1273339941_copy-of-cms-lead-image-12.jpg',
       },
       { id:27,
        cat:'Hollywood',
        name:'BLACKPINK surpasses Bad Bunny',
      heading:'BLACKPINK surpasses Bad Bunny, Justin Bieber to become first music artist with 33 billion views BLACKPINK is the first music artist in the world to accumulate 33 billion views on YouTube surpassing musicians like Bad Bunny',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-09/1130431308_blackpink.jpg',
       },
       { id:28,
        cat:'Hollywood',
        name:'Selena Gomez has an eye-popping reaction',
      heading:'Selena Gomez has an eye-popping reaction during Olivia Rodrigo VMA performance collapse; Details inside Did you know that during Olivia Rodrigo performance at the VMAs, there was a stage disaster that elicited a horrified reaction from Selena Gomez? ',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-09/124847245_img-20230913-wa0026.jpg',
       },
       { id:29,
        cat:'Hollywood',
        name:'‘I don’t have beef with anyone’',
      heading:'‘I don’t have beef with anyone’: Olivia Rodrigo clarifies Taylor Swift feud rumors, calls herself ‘very chill’ Olivia Rodrigo sets the record straight about ongoing rumors of a feud between her and Taylor Swift',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-09/615895897_57019832_olivia-rodrigo.jpg',
       },
       { id:30,
        cat:'Hollywood',
        name:'Golden Globes 2023',
      heading:'Golden Globes 2023: What made host Jerrod Carmichael roast-filled monologue stand out? 3 EPIC jokes by him Jerrod Carmichael became the first Black host to introduce the prestigious Golden Globe Awards 2023. Read on to find out more about the comedian, writer, and actor.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://www.pinkvilla.com/images/2023-01/549958785_jerrod-carmichael-golden-globe-awards_1280*720.jpg',
       },
       { id:31,
        cat:'Technology',
        name:'Arm: UK chip designer in $54.5bn market return',
      heading:'UK-based chip designer Arm Holdings has secured a $54.5bn (£43.6bn) valuation, as it makes its highly-anticipated return to the stock market The shares were priced at $51 each.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/1846E/production/_131083499_gettyimages-1660490157.jpg.webp',
       },
       { id:32,
        cat:'Technology',
        name:'Babcock Ranch: Florida first hurricane-proof town',
      heading:'Babcock Ranch: Florida first hurricane-proof town Florida Babcock Ranch was built to survive a storm. Hurricane Ian was the town first test. Incredibly, the community.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ychef.files.bbci.co.uk/1280x720/p0gbm9my.jpg',
       },
       { id:33,
        cat:'Technology',
        name:'The gold jewellery made from old phones',
      heading:'The gold jewellery made from old phones E-waste is mounting. Now the UK Royal Mint has found a new way to extract the precious metals hidden in laptops and phones to reduce.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ychef.files.bbci.co.uk/1600x900/p0g9lvyb.webp',
       },
       { id:34,
        cat:'Technology',
        name:'The place where no humans will tread for 100,000 years',
      heading:'In a few years, Finland will begin depositing spent nuclear fuel underground in Onkalo, where it will remain for millennia. Erika Benke describes her experience . ',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ychef.files.bbci.co.uk/1600x900/p0g8jkbp.webp',
       },
       { id:35,
        cat:'Technology',
        name:'iPhone 15: Apple forced to ditch lightning charger',
      heading:'Apple has confirmed its new iPhone will not feature its proprietary lightning charging port, after the EU forced the change.The tech giant said that the iPhone 15, unveiled at its annual event on Tuesday, would use a USB-C cable as the "universally accepted standard".',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/12509/production/_131071057_all_colors__d4w03v51nwcy_large_2x.jpg.webp',
       },
       { id:36,
        cat:'Technology',
        name:'Libya flood: Satellite images and aerial photographs show destruction',
      heading:'Satellite images show the scale of destruction in the Libyan port of Derna after floodwaters swept away bridges, streets and communities - leaving thousands of people missing or dead.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/69C6/production/_131087072_gettyimages-1663035259_derna976.jpg.webp',
       },
       { id:37,
        cat:'Technology',
        name:'Google antitrust trial: Tech giant denies abusing power to gain monopoly',
      heading:'Google has dismissed arguments that it is the worlds biggest search engine because of illegal practices, saying to switch to another company takes "literally four taps".',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/AAC5/production/_131071734_gettyimages-1676132731.jpg.webp',
       },
       { id:38,
        cat:'Technology',
        name:'Cryptoqueen: Accomplice jailed for 20 years for OneCoin financial scam',
      heading:'A co-founder of the fraudulent OneCoin cryptocurrency has been sentenced to serve 20 years in a US prison.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/3176/production/_109526621_fbe30e2c-6d48-4161-8c2a-6f0731e423f6.jpg.webp',
       },
       { id:39,
        cat:'Technology',
        name:'Unity engine: Among Us and Slay the Spire makers join criticism',
      heading:'What do hit indie games Among Us, Slay the Spire and Cult of the Lamb all have in common? They are all made with the Unity engine - a development tool thats popular with smaller studios.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/D280/production/_131088835_2aaqtf-w.png.webp',
       },
       { id:40,
        cat:'Technology',
        name:'Gamescom: The biggest announcements at the show',
      heading:'Space, alternative reality and a stage invasion organisers would probably rather forget were among the highlights from this years Gamescom.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/16EC8/production/_130869839_8914af2ec232c65d5687d3e19b8aa7b60c6ab97c.jpg.webp',
       },
       { id:41,
        cat:'Technology',
        name:'A journey into space with Starfield',
      heading:'We are now just days away from the launch of this huge space adventure, which promises an open world spanning multiple planets.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/179E/production/_130064060_starfield_03_exploringplanets.png.webp',
       },
       { id:42,
        cat:'Technology',
        name:'Bristol to host one of Europe most powerful supercomputers',
      heading:'A new supercomputer set to be one of the most powerful in Europe is to be built in a move to drive AI research in the UK, the government says.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/11858/production/_131086717_2b51c145-0f55-48e9-9b57-bc450149ebb7.jpg.webp',
       },
       { id:43,
        cat:'Technology',
        name:'France halts iPhone 12 sales over radiation levels',
      heading:'France has ordered Apple to stop selling the iPhone 12 for emitting too much electromagnetic radiation.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/C893/production/_131074315_mediaitem131074314.jpg.webp',
       },
       { id:44,
        cat:'Technology',
        name:'Long wave radio fans mourn fading frequencies',
      heading:'As he turned the dial gently but purposefully, the sound of people speaking in foreign languages and the lilt of unfamiliar music burst through a haze of crackle and buzz.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/10588/production/_130925966_clintgouveia1-credit-clintgouveia.jpg.webp',
       },
       { id:45,
        cat:'Technology',
        name:'Robots are trained to help revive coral reefs',
      heading:'Its a really special part of the world," says marine biologist Taryn Foster from the Abrolhos Islands, 40 miles from the coast of Western Australia.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://ichef.bbci.co.uk/news/976/cpsprodpb/13239/production/_130939387_traininginsf.jpg.webp',
       },
       { id:46,
        cat:'Fitness',
        name:'Myths And Facts: Debunking Misconceptions On Water Role In Your Weight Loss Journey',
      heading:'Drinking water can indirectly support your weight loss journey by curbing appetite, aiding digestion, and helping you make better food choices.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/09/13/1280296-weight-water.png?im=FitAndFill=(700,400)',
       },
       { id:47,
        cat:'Fitness',
        name:'Yoga For Seniors: Age Gracefully With 5 Daily Asanas For Strength, Flexibility And Balance',
      heading:'Yoga offers older people a holistic approach to ageing gracefully. From improving physical health to balance here are some daily yoga asanas to practice.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/09/11/1278723-elderly-yoga.png?im=FitAndFill=(700,400)',
       },
       { id:48,
        cat:'Fitness',
        name:'Diabetes And Travel: 11 Tips For Managing Your Blood Sugar Levels On The Go',
      heading:'Read on to discover how you can maintain control of your diabetes while exploring new destinations or travelling for work. Here are some valuable insights .',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/09/11/1278720-diabetes-travel.png?im=FitAndFill=(700,400)',
       },
       { id:49,
        cat:'Fitness',
        name:'Sleep Hygiene: Proven Tips For A Good Night Rest In A Busy World',
      heading:'Prioritizing sleep in our busy lives is crucial for overall well-being. To achieve better sleep, consider the following practical tips.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/09/11/1278714-sleep-hygiene.png?im=FitAndFill=(700,400)',
       },
       { id:50,
        cat:'Fitness',
        name:'Trim Down Deliciously: 3 Indian Breakfasts To Add To Your Weight Loss Diet',
      heading:'Achieving weight loss while enjoying Indian dishes requires mindful choices. Here are some tasty yet health Indian dishes that you must eat if you are on a weight loss diet.',description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/09/09/1277980-weight-dieting.png?im=FitAndFill=(700,400)',
       },
       { id:51,
        cat:'Fitness',
        name:'Hair Health And Wellness: How Diet And Exercise Affect Your Tresses',
      heading:'A balanced diet and an active lifestyle are essential components of a comprehensive hair care routine.  Make mindful choices when it comes to what you eat and how you move, and your locks will thank you with their shine and resilience.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/09/06/1276489-hair-fun.png?im=FitAndFill=(700,400)',
       },
       { id:52,
        cat:'Fitness',
        name:'High Cholesterol? Try These 5 Indian Kitchen Remedies For Better Health',
      heading:'Did you know high cholesterol levels can be managed with the help of desi remedies from your kitchen! Here are kitchen secrets that can help you keep high cholesterol woes at bay.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/09/06/1276033-kitchen-staples.png?im=FitAndFill=(700,400)',
       },
       { id:53,
        cat:'Fitness',
        name:'Hepatitis: More Than 50% Of Individuals Suffer From Liver Inflammation',
      heading:'Hepatitis is a term used to describe liver inflammation. It can be caused by a variety of reasons such as viral infections, alcoholism, certain drugs, autoimmune problems, toxins, and metabolic disorders.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/08/22/1267512-doctor-patient-1.png?im=FitAndFill=(700,400)',
       },
       { id:54,
        cat:'Fitness',
        name:'Wish To Live Longer? Eating A Plant-Based Diet',
      heading:'In a study of adults in the UK, those who adhered closely to a Mediterranean lifestyle had lower risk of all-cause and cancer mortality. Find out more!',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/08/19/1265973-dietexercise.png?im=FitAndFill=(700,400)',
       },
       { id:55,
        cat:'Fitness',
        name:'World Organ Donation Day 2023',
      heading:'World Organ Donation Day is observed every year on August 13 to encourage people to become an organ donor and to clear up misconceptions about organ donation.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/08/13/1261900-organ-donation.png?im=FitAndFill=(700,400)',
       },
       { id:56,
        cat:'Fitness',
        name:'Exclusive: Does Alcohol Affect Women Differently Than Men? ',
      heading:'Excessive alcohol use poses unique health and safety risks to females which is a little different than how it affects men. A general physician shares if women are more susceptible to the effects of alcohol and more, read on.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/08/12/1261459-alcohol-women.png?im=FitAndFill=(700,400)',
       },
       { id:57,
        cat:'Fitness',
        name:'8 Yoga Asanas You Must Practice To Increase Stamina',
      heading:'Whether you are a beginner or an experienced yogi, integrating these poses into your routine can provide a well-rounded approach to increasing your overall stamina and elevating your physical prowess.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/08/07/1257890-surya-namaskar.jpg?im=FitAndFill=(700,400)',
       },
       { id:58,
        cat:'Fitness',
        name:'Fitness Regime: 5 Health Benefits Of Adding Whey Protein Supplements',
      heading:'Whether you aim to build muscles, enhance recovery, or improve overall health, whey protein can be a valuable addition to your dietary routine.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/08/01/1253904-whey-protein.jpg?im=FitAndFill=(700,400)',
       },
       { id:59,
        cat:'Fitness',
        name:'PCOS Diet: 5 Food Habits That Can Help Manage Polycystic Ovary Syndrome',
      heading:'There is no recommended diet for PCOS or polycystic ovarian syndrome. However, some food habits, such as eating a diet which is anti-inflammation, may help control some symptoms. Read on to know more.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/07/29/1251605-pcos-diet.png?im=FitAndFill=(700,400)',
       },
       { id:60,
        cat:'Fitness',
        name:'Does Snacking Impact Your Health?',
      heading:'Love to munch on snacks in between your meals? Beware, late-night nibbles or snacking on highly processed foods could negatively affect health, according to a study.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/07/26/1249899-snacks-binge.png?im=FitAndFill=(700,400)',
       },
       { id:61,
        cat:'Food',
        name:'9 New Restaurants You Must Visit in September for Delish Delicacies',
      heading:'In the vibrant culinary landscape of September, a new gastronomic gem is set to dazzle taste buds and delight food enthusiasts. As the season’s leaves begin to change.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/09/untitled-design-69-16941894493x2.png?impolicy=website&width=510&height=356',
       },
       { id:62,
        cat:'Food',
        name:'Janmashtami 2023: 11 Exquisite Recipes For Janmashtami Celebrations',
      heading:'Janmashtami, a revered festival in India, holds profound significance as it commemorates the birth anniversary of Lord Krishna the birth anniversary of Lord Krishna. ',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/09/untitled-design-45-16940085573x2.png?impolicy=website&width=510&height=356',
       },
       { id:63,
        cat:'Food',
        name:'World Samosa Day 2023: Mastering the Art of Crisp Samosas With Expert Tips and Tricks',
      heading:'Crispy samosas make any occasion, no matter how little or large, more enjoyable, whether it be an office party, a small family gathering.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/07/untitled-design-77-1-16896760343x2.png?impolicy=website&width=510&height=356',
       },
       { id:64,
        cat:'Food',
        name:'An Exquisite New Menu to Delight Guests Palates called Prarambh In Town',
      heading:'Made in India, Radisson MBD Noida, one of the premier hotels in the NCR region, is thrilled to announce the launch of its new menu prarambh (the beginning) that is set to tantalize taste buds .',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/09/untitled-design-29-16938059373x2.png?impolicy=website&width=510&height=356',
       },
       { id:65,
        cat:'Food',
        name:'Importance of Eating The Right Food Combinations',
      heading:'Food pairing and nutrient interaction are two concepts that have been explored and researched extensively over a long period of time to identify the relationship between particular foods.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/07/harshit-pandey-2023-07-03t110200.985-16883623863x2.png?impolicy=website&width=510&height=356',
       },
       { id:66,
        cat:'Food',
        name:'Brands Are Redefining Culinary Excellence and Expansion in the Fast-Food Industry',
      heading:'The concept of redefining culinary excellence and expansion in the fast-food industry is transcending traditional boundaries.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/06/untitled-design-2023-06-16t180445.420-16869188963x2.jpg?impolicy=website&width=510&height=356',
       },
       { id:67,
        cat:'Food',
        name:'Rakshabandhan 2023: 5 Unconventional Ways to Celebrate Raksha Bandhan with Ice Creams',
      heading:'This Raksha Bandhan, let’s shake things up and have a blast. Alongside the classic Indian sweets, why not toss in some delightful ice-creams? Imagine the extra smiles that’ll bring!',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/07/untitled-design-2023-07-31t123324.830-16907870503x2.jpg?impolicy=website&width=510&height=356',
       },
       { id:68,
        cat:'Food',
        name:'How Gen Z Is Driving The Salads Trend Globally And Making It Look Fashionable',
      heading:' the dynamic Gen Z demographic is reshaping global dining preferences by propelling salads into the spotlight of trendiness. Their embrace of health-conscious choices has breathed new life into salads, turning them into more than just a meal but a fashion statement.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/08/untitled-design-246-16932048053x2.png?impolicy=website&width=510&height=356',
       },
       { id:69,
        cat:'Food',
        name:'Onam 2023: 3 Traditional Recipes You Must Try Out This Festive Season',
      heading:'The Onam festivities have begun and so has all the enjoyment that definitely does include food. Believe it or not, food plays an imperative role in every Indian festival',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/08/untitled-design-69-1-16931277643x2.png?impolicy=website&width=510&height=356',
       },
       { id:70,
        cat:'Food',
        name:'Savoring India Tea Odyssey: A Sip through Time',
      heading:'Chai- It is that one loving companion that we have truly accepted, in all its forms and flavours. In the book Chai: The Experience of Indian Tea, authors Rajan Kapoor and Rekha Sarin state',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/06/untitled-2023-06-23t142518.131-16875108083x2.jpg?impolicy=website&width=510&height=356',
       },
       { id:71,
        cat:'Food',
        name:'Millet: The Modern Superfood Finding Favor in India',
      heading:'Millets are present in cuisines across the country, be it Punjab’s bajre di roti, mudde or hittu in Karnataka and Andhra Pradesh, ragi kali in Tamil Nadu, or jowar bhakri in Maharashtra.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/04/wp-image-848-16820783943x2.jpg?impolicy=website&width=510&height=356',
       },
       { id:72,
        cat:'Food',
        name:'Peanut Butter Fusion: A Global Twist on Classic Dishes',
      heading:'Combining global flavors, this inventive approach reimagines classic recipes. From savory to sweet, discover a harmonious blend of cultures, all united by the rich and nutty essence of peanut butter. ',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/08/shutterstock_1829416040-16917276463x2.jpg?impolicy=website&width=510&height=356',
       },
       { id:73,
        cat:'Food',
        name:'6 Extremely Unique and Fabulously Curated Wine Glasses for a Spectacular Sensory Experience',
      heading:'Wine glasses come in a variety of sizes and forms, each created to enhance the flavours and aromas of a particular wine kind. The bowl, stem, and base are the three primary parts of a wine glass.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/08/lead1-16923568543x2.jpg?impolicy=website&width=510&height=356',
       },
       { id:74,
        cat:'Food',
        name:'Raksha Bandhan 2023: 3 Amazing Rakhi Recipes to Cherish Sibling Love',
      heading:'On this day, sisters wrap their brothers’ wrists in a rakhi, a sacred thread that denotes love and protection. Brothers promise to protect their sisters and give them presents in exchange.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/08/image-4-16923636683x2.jpg?impolicy=website&width=510&height=356',
       },
       { id:75,
        cat:'Food',
        name:'Navroz 2023: 6 Traditional Recipes You Must Try This Parsi New Year',
      heading:'Parsi New Year 2023: Here is a list of six traditional Parsi recipes that exemplify the flavours and culinary customs of this vibrant community. These dishes not only tantalize the taste buds but also carry stories of generations past and heritage.',
      description:'Many people look for ways to expand their online presence and while one of the most popular strategies is launching a blog, not everyone knows what is a blog and how to start one. When blogs first emerged around 1994, people used them mainly to share their personal lives, including their experiences and interests. Now, blogs have become an essential online marketing strategy for businesses and one of the most profitable career choices for individuals.The interface of blogs has changed significantly over time. Bloggers can now integrate various widgets and plugins into their platforms, such as a social media feed, a contact form, or an author profile.',
      bollywoodimg:'https://images.news18.com/ibnlive/uploads/2023/08/parsi-new-year-2023-foods-16920135103x2.jpg?impolicy=website&width=510&height=356',
       },
       
       
    ])
  return (
    <div>
      <Store.Provider value={[data,setData]}>
        {props.children}
      </Store.Provider>
    </div>
  )
}

export default ContextAPI
